upd: obtain script

diff --git a/.scripts/obtain-udocker b/.scripts/obtain-udocker
--- a/.scripts/obtain-udocker
+++ b/.scripts/obtain-udocker
@@ -1,15 +1,17 @@
 #!/bin/bash
-set -e
-echo "==== Obtain UDocker ===="
+echo "==== Obtaining UDocker ===="
 exe=udocker
 url=https://raw.githubusercontent.com/infinitus-inanis/udocker/main/$exe
 pushd /tmp > /dev/null
-  curl $url -o $exe
+  curl -s $url -o $exe
   install_dir=${DESTDIR:-}${PREFIX:-/usr}/bin
   install_path=$install_dir/$exe
   install -d $install_dir
   install -m 755 $exe $install_dir
-  echo "== Installed at: $install_path"
+  if [ $? -eq 0 ]; then
+    echo "== Installed at: $install_path"
+  else
+    echo "== Failed to install at: $install_path"
+  fi
   rm -f $exe
 popd > /dev/null
-echo "== Done =="
